# Generated by Django 5.2.14 on 2026-05-21 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('original_prompt', models.TextField()),
                ('resolved_dataset', models.TextField(blank=True, default='')),
                ('backend_profile', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('queue_message_id', models.CharField(blank=True, default='', max_length=128)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('queue_position', models.PositiveIntegerField(blank=True, null=True)),
                ('queue_depth', models.PositiveIntegerField(blank=True, null=True)),
                ('execution_timeout_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('runtime_seconds', models.FloatField(blank=True, null=True)),
                ('generated_code_preview', models.TextField(blank=True, default='')),
                ('failure_message', models.TextField(blank=True, default='')),
                ('result_metadata', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_kind', models.CharField(choices=[('report', 'Report'), ('plot', 'Plot'), ('script', 'Script'), ('log', 'Log'), ('bundle', 'Bundle')], max_length=16)),
                ('blob_container', models.CharField(max_length=128)),
                ('blob_key', models.CharField(max_length=512)),
                ('content_type', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('is_canonical', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='portal.job')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('service', 'Service')], default='user', max_length=16)),
                ('approval_state', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_user_profiles', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_user_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['owner', 'status'], name='job_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['submission_id'], name='job_submission_id_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'submitted_at'], name='job_status_submitted_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('retry_count__gte', 0)), name='job_retry_count_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='jobartifact',
            index=models.Index(fields=['job', 'artifact_kind'], name='artifact_job_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobartifact',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gte', 0)), name='artifact_size_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['approval_state'], name='profile_state_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='profile_role_idx'),
        ),
    ]
