# Generated by Django 5.2.14 on 2026-05-21 11:32

import django.db.models.deletion
import django.utils.timezone
import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueMessageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(default=portal.models._queue_message_id, editable=False, max_length=32, unique=True)),
                ('backend_profile', models.CharField(max_length=64)),
                ('body', models.TextField()),
                ('dequeue_count', models.PositiveIntegerField(default=0)),
                ('pop_receipt', models.CharField(blank=True, default='', max_length=64)),
                ('visible_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_messages', to='portal.job')),
            ],
            options={
                'indexes': [models.Index(fields=['visible_at', 'created_at'], name='queue_visible_created_idx'), models.Index(fields=['job'], name='queue_job_idx')],
            },
        ),
    ]
