# Generated by Django 5.2.14 on 2026-05-21 12:17

import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_queuemessagerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuemessagerecord',
            name='message_id',
            field=models.CharField(default=portal.models._queue_message_id, editable=False, max_length=128, unique=True),
        ),
    ]
