#!/usr/bin/env python
import os
import sys

from portal.plot_runner_cli import main


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "run":
        raise SystemExit(main(sys.argv[1:]))

    os.execvp(
        sys.executable,
        [sys.executable, "manage.py", *sys.argv[1:]],
    )
