from __future__ import annotations

import argparse
import json
from pathlib import Path


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _fake_generated_script(job_id: str, prompt: str) -> str:
    return "\n".join(
        [
            "# Generated by the local plot driver.",
            f"# Submission: {job_id}",
            f"# Prompt: {prompt}",
            "",
            "print('hello from the local plot driver')",
        ]
    )


def _fake_comments(job_id: str, prompt: str) -> str:
    return "\n".join(
        [
            f"# Comments for {job_id}",
            "",
            prompt,
        ]
    )


def _fake_svg(job_id: str, backend_profile: str) -> str:
    return "\n".join(
        [
            '<svg xmlns="http://www.w3.org/2000/svg" width="640" height="320">',
            '<rect width="100%" height="100%" fill="white"/>',
            '<text x="24" y="48" font-size="24" fill="black">Local plot driver</text>',
            f'<text x="24" y="88" font-size="16" fill="black">{backend_profile}</text>',
            f'<text x="24" y="120" font-size="16" fill="black">{job_id}</text>',
            "</svg>",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--job-id", required=True)
    parser.add_argument("--work-dir", required=True)
    parser.add_argument("--prompt-path", required=True)
    parser.add_argument("--context-path", required=True)
    parser.add_argument("--fail", action="store_true")
    args = parser.parse_args()

    work_dir = Path(args.work_dir)
    prompt = Path(args.prompt_path).read_text(encoding="utf-8").strip()
    context = json.loads(Path(args.context_path).read_text(encoding="utf-8"))

    log_path = work_dir / "run.log"
    script_path = work_dir / "generated.py"
    comments_path = work_dir / "comments.md"
    plot_path = work_dir / "plot.svg"

    _write_text(log_path, f"driver started for {args.job_id}\n")
    _write_text(script_path, _fake_generated_script(args.job_id, prompt))
    _write_text(comments_path, _fake_comments(args.job_id, prompt))

    if args.fail:
        _write_text(log_path, log_path.read_text(encoding="utf-8") + "driver failed\n")
        return 2

    _write_text(
        plot_path,
        _fake_svg(args.job_id, str(context.get("backend_profile", ""))),
    )
    _write_text(log_path, log_path.read_text(encoding="utf-8") + "driver completed\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
