from __future__ import annotations

import argparse
import json
import os
import subprocess
from pathlib import Path


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _append_log(work_dir: Path, content: str) -> None:
    log_path = work_dir / "run.log"
    previous = log_path.read_text(encoding="utf-8") if log_path.exists() else ""
    _write_text(log_path, previous + content)


def _fake_generated_script(job_id: str, prompt: str) -> str:
    return "\n".join(
        [
            "# Generated by the fake local plot driver.",
            f"# Submission: {job_id}",
            f"# Prompt: {prompt}",
            "",
            "print('hello from the local plot driver')",
        ]
    )


def _fake_comments(job_id: str, prompt: str) -> str:
    return "\n".join(
        [
            f"# Comments for {job_id}",
            "",
            prompt,
        ]
    )


def _fake_svg(job_id: str, backend_profile: str) -> str:
    return "\n".join(
        [
            '<svg xmlns="http://www.w3.org/2000/svg" width="640" height="320">',
            '<rect width="100%" height="100%" fill="white"/>',
            '<text x="24" y="48" font-size="24" fill="black">Local plot driver</text>',
            f'<text x="24" y="88" font-size="16" fill="black">{backend_profile}</text>',
            f'<text x="24" y="120" font-size="16" fill="black">{job_id}</text>',
            "</svg>",
        ]
    )


def build_codex_command(work_dir: Path, output_last_message: Path) -> list[str]:
    return [
        "codex",
        "exec",
        "--cd",
        str(work_dir),
        "--skip-git-repo-check",
        "--ignore-user-config",
        "--dangerously-bypass-approvals-and-sandbox",
        "--output-last-message",
        str(output_last_message),
    ]


def _codex_prompt(job_id: str, prompt: str, context: dict[str, object]) -> str:
    backend_profile = str(context.get("backend_profile", ""))
    resolved_dataset = str(context.get("resolved_dataset", ""))
    return "\n".join(
        [
            f"You are the plot runner for job {job_id}.",
            "Read prompt.txt and context.json in the current working directory.",
            "Create generated.py and comments.md in the current working directory.",
            "generated.py must be a stand-alone Python script that produces the "
            "requested plot when run.",
            "If you need Python dependencies, make generated.py compatible with "
            "`uv run generated.py`.",
            "After writing generated.py, run `uv run generated.py` so plot.svg is "
            "produced in the current directory.",
            "Do not write secrets into any file.",
            "",
            f"backend_profile: {backend_profile}",
            f"resolved_dataset: {resolved_dataset}",
            "",
            "plot request:",
            prompt,
        ]
    )


def _run_codex_driver(job_id: str, work_dir: Path, prompt: str, context: dict[str, object]) -> int:
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        _append_log(work_dir, "OPENAI_API_KEY is required for codex mode\n")
        return 3

    output_last_message = work_dir / "codex-last-message.md"
    command = build_codex_command(work_dir, output_last_message)
    env = os.environ.copy()

    completed = subprocess.run(
        command,
        cwd=work_dir,
        env=env,
        capture_output=True,
        text=True,
        input=_codex_prompt(job_id, prompt, context),
        check=False,
    )
    _append_log(
        work_dir,
        "".join(
            [
                completed.stdout or "",
                completed.stderr or "",
                f"codex exit code {completed.returncode}\n",
            ]
        ),
    )
    if completed.returncode != 0:
        return completed.returncode

    generated_script = work_dir / "generated.py"
    if not generated_script.exists():
        _append_log(work_dir, "generated.py was not created\n")
        return 4

    uv_completed = subprocess.run(
        ["uv", "run", "generated.py"],
        cwd=work_dir,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )
    _append_log(
        work_dir,
        "".join(
            [
                uv_completed.stdout or "",
                uv_completed.stderr or "",
                f"uv exit code {uv_completed.returncode}\n",
            ]
        ),
    )
    if uv_completed.returncode != 0:
        return uv_completed.returncode
    if not (work_dir / "plot.svg").exists():
        _append_log(work_dir, "plot.svg was not created\n")
        return 5
    return 0


def _run_fake_driver(
    job_id: str,
    work_dir: Path,
    prompt: str,
    context: dict[str, object],
    *,
    fail: bool,
) -> int:
    backend_profile = str(context.get("backend_profile", ""))
    _write_text(work_dir / "generated.py", _fake_generated_script(job_id, prompt))
    _write_text(work_dir / "comments.md", _fake_comments(job_id, prompt))
    _write_text(work_dir / "run.log", f"driver started for {job_id}\n")

    if fail:
        _append_log(work_dir, "driver failed\n")
        return 2

    _write_text(work_dir / "plot.svg", _fake_svg(job_id, backend_profile))
    _append_log(work_dir, "driver completed\n")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--job-id", required=True)
    parser.add_argument("--work-dir", required=True)
    parser.add_argument("--prompt-path", required=True)
    parser.add_argument("--context-path", required=True)
    parser.add_argument("--executor", default=os.environ.get("PLOT_DRIVER_EXECUTOR", "fake"))
    parser.add_argument("--fail", action="store_true")
    args = parser.parse_args()

    work_dir = Path(args.work_dir)
    prompt = Path(args.prompt_path).read_text(encoding="utf-8").strip()
    context = json.loads(Path(args.context_path).read_text(encoding="utf-8"))

    if args.fail:
        _append_log(work_dir, "driver failed\n")
        return 2

    if args.executor == "codex":
        return _run_codex_driver(args.job_id, work_dir, prompt, context)
    if args.executor == "fake":
        return _run_fake_driver(args.job_id, work_dir, prompt, context, fail=False)

    _append_log(work_dir, f"unknown executor: {args.executor}\n")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
