from __future__ import annotations

import tempfile
from dataclasses import dataclass
from pathlib import Path
from time import monotonic

from django.conf import settings

from portal.artifacts import ArtifactRef, LocalArtifactStore
from portal.models import ArtifactKind, Job, JobArtifact
from portal.services import claim_job, mark_completed, mark_failed


@dataclass(frozen=True, slots=True)
class RunnerResult:
    job: Job
    artifact_refs: tuple[ArtifactRef, ...]


def _artifact_store() -> LocalArtifactStore:
    return LocalArtifactStore(Path(settings.ARTIFACT_STORAGE_ROOT))


def _runner_root() -> Path:
    root = Path(settings.BASE_DIR) / "tmp" / "plot-runner"
    root.mkdir(parents=True, exist_ok=True)
    return root


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _record_artifact(job: Job, ref: ArtifactRef) -> JobArtifact:
    return JobArtifact.objects.create(
        job=job,
        artifact_kind=ref.artifact_kind,
        blob_container=ref.blob_container,
        blob_key=ref.blob_key,
        content_type=ref.content_type,
        size_bytes=ref.size_bytes,
        is_canonical=ref.is_canonical,
    )


def _fake_generated_script(job: Job) -> str:
    return "\n".join(
        [
            "# Generated by the fake local plot runner.",
            f"# Submission: {job.submission_id}",
            f"# Prompt: {job.original_prompt}",
            "",
            "print('hello from the fake plot runner')",
        ]
    )


def _fake_comments(job: Job) -> str:
    return "\n".join(
        [
            f"# Comments for {job.submission_id}",
            "",
            job.original_prompt,
        ]
    )


def _fake_svg(job: Job) -> str:
    return "\n".join(
        [
            '<svg xmlns="http://www.w3.org/2000/svg" width="640" height="320">',
            '<rect width="100%" height="100%" fill="white"/>',
            '<text x="24" y="48" font-size="24" fill="black">Fake plot</text>',
            f'<text x="24" y="88" font-size="16" fill="black">{job.backend_profile}</text>',
            f'<text x="24" y="120" font-size="16" fill="black">{job.submission_id}</text>',
            "</svg>",
        ]
    )


def run_fake_plot_job(job_id: str, *, fail: bool = False) -> RunnerResult:
    job = claim_job(job_id)
    started = monotonic()
    refs: list[ArtifactRef] = []

    try:
        with tempfile.TemporaryDirectory(dir=_runner_root()) as temp_dir:
            work_dir = Path(temp_dir)
            script_path = work_dir / "generated.py"
            comments_path = work_dir / "comments.md"
            plot_path = work_dir / "plot.svg"
            log_path = work_dir / "run.log"

            _write_text(script_path, _fake_generated_script(job))
            _write_text(comments_path, _fake_comments(job))
            _write_text(log_path, f"runner started for {job.submission_id}\n")

            if fail:
                _write_text(log_path, log_path.read_text(encoding="utf-8") + "simulated failure\n")
                script_ref = _artifact_store().put_artifact(
                    job_id=str(job.submission_id),
                    local_path=script_path,
                    artifact_kind=ArtifactKind.SCRIPT,
                    content_type="text/x-python",
                    is_canonical=True,
                )
                refs.append(script_ref)
                refs.append(
                    _artifact_store().put_artifact(
                        job_id=str(job.submission_id),
                        local_path=log_path,
                        artifact_kind=ArtifactKind.LOG,
                        content_type="text/plain",
                        is_canonical=True,
                    )
                )
                for ref in refs:
                    _record_artifact(job, ref)
                job = mark_failed(job, failure_message="Simulated plot runner failure")
                return RunnerResult(job=job, artifact_refs=tuple(refs))

            _write_text(plot_path, _fake_svg(job))
            _write_text(log_path, log_path.read_text(encoding="utf-8") + "simulated success\n")

            refs.extend(
                [
                    _artifact_store().put_artifact(
                        job_id=str(job.submission_id),
                        local_path=script_path,
                        artifact_kind=ArtifactKind.SCRIPT,
                        content_type="text/x-python",
                        is_canonical=True,
                    ),
                    _artifact_store().put_artifact(
                        job_id=str(job.submission_id),
                        local_path=comments_path,
                        artifact_kind=ArtifactKind.REPORT,
                        content_type="text/markdown",
                        is_canonical=True,
                    ),
                    _artifact_store().put_artifact(
                        job_id=str(job.submission_id),
                        local_path=plot_path,
                        artifact_kind=ArtifactKind.PLOT,
                        content_type="image/svg+xml",
                        is_canonical=True,
                    ),
                    _artifact_store().put_artifact(
                        job_id=str(job.submission_id),
                        local_path=log_path,
                        artifact_kind=ArtifactKind.LOG,
                        content_type="text/plain",
                        is_canonical=True,
                    ),
                ]
            )
            for ref in refs:
                _record_artifact(job, ref)

            elapsed = monotonic() - started
            job = mark_completed(
                job,
                result_metadata={
                    "artifacts": [ref.blob_key for ref in refs],
                    "runtime_seconds": round(elapsed, 3),
                },
            )
            Job.objects.filter(pk=job.pk).update(runtime_seconds=elapsed)
            return RunnerResult(job=job, artifact_refs=tuple(refs))
    except Exception as exc:
        job = mark_failed(job, failure_message=f"Runner crashed: {exc}")
        return RunnerResult(job=job, artifact_refs=tuple(refs))
